name: sid_newbp_mono_colab_debug
model_type: LowlightModel
num_gpu: 0
manual_seed: 0

network_g:
  type: NewBPNAFNet
  in_channels: 3
  kernel_type: panchromatic
  kernel_spec: P2
  width: 16
  enc_blk_nums: [1, 1, 1, 1]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

datasets:
  train:
    name: dummy
    type: PairedImageDataset
    dataroot_gt: ./dummy_gt
    dataroot_lq: ./dummy_lq
    io_backend:
      type: disk
  val:
    name: dummy_val
    type: PairedImageDataset
    dataroot_gt: ./dummy_gt
    dataroot_lq: ./dummy_lq
    io_backend:
      type: disk

train:
  optim_g:
    type: AdamW
    lr: 0.0001
    weight_decay: 0.0
    betas: [0.9, 0.999]
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
  total_iter: 4
  lr_scheduler:
    type: MultiStepLR
    milestones: [2]
    gamma: 0.5

path:
  root: .

logger:
  use_tb_logger: false
